#MONGO_ENV: {DB: test-application, URI: 'mongodb://localhost:27017/test-application'}
MONGO_ENV: {DB: test-application, URI: 'mongodb://heimdall:lzIVsf192KCp@ds039267.mongolab.com:39267/test-application'}
MQ_ENV: {PROJECT: '519514072267d87d270009d3',  TOKEN: '3_XQjebvatOGUd_7uWujEbNnT5g', HOST: 'mq-rackspace-ord.iron.io'}
SOCIALGIST_SUBSCRIPTION_URL: 'https://soshio.socialgist.com/stream/sinaweibo_main/subscription/main/part/1/data.json'
SOCIALGIST_KEYWORD_URL: 'https://api.socialgist.com/keywordapi/soshio/sinaweibo/main/keywords'
